// <auto-generated />
using System;
using ClinicAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicAPI.DAL.Migrations
{
    [DbContext(typeof(ClinicAPIDbContext))]
    [Migration("20250610105418_primeira tentativa")]
    partial class primeiratentativa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicAPI.Model.ActoClinico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAgendada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRealizada")
                        .HasColumnType("datetime2");

                    b.Property<int>("PedidoMarcacaoId")
                        .HasColumnType("int");

                    b.Property<int>("ProfissionalId")
                        .HasColumnType("int");

                    b.Property<int>("SubsistemaSaudeId")
                        .HasColumnType("int");

                    b.Property<int>("TipoServicoClinicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoMarcacaoId");

                    b.HasIndex("ProfissionalId");

                    b.HasIndex("SubsistemaSaudeId");

                    b.HasIndex("TipoServicoClinicoId");

                    b.ToTable("ActosClinicos");
                });

            modelBuilder.Entity("ClinicAPI.Model.PedidoMarcacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFimPreferencial")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioPreferencial")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("HorarioPreferencial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotasAdicionais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId");

                    b.ToTable("PedidoMarcacoes");
                });

            modelBuilder.Entity("ClinicAPI.Model.Profissional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profissionais");
                });

            modelBuilder.Entity("ClinicAPI.Model.SubsistemaSaude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubsistemasSaude");
                });

            modelBuilder.Entity("ClinicAPI.Model.TipoServicoClinico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EExame")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposServicosClinicos");
                });

            modelBuilder.Entity("ClinicAPI.Model.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Morada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeUtente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telemovel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Utentes");
                });

            modelBuilder.Entity("ClinicAPI.Model.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUtilizador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("ClinicAPI.Model.ActoClinico", b =>
                {
                    b.HasOne("ClinicAPI.Model.PedidoMarcacao", "PedidoMarcacao")
                        .WithMany("ActosClinicos")
                        .HasForeignKey("PedidoMarcacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAPI.Model.Profissional", "Profissional")
                        .WithMany("ActosClinicos")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAPI.Model.SubsistemaSaude", "SubsistemaSaude")
                        .WithMany("ActosClinicos")
                        .HasForeignKey("SubsistemaSaudeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAPI.Model.TipoServicoClinico", "TipoServicoClinico")
                        .WithMany("ActosClinicos")
                        .HasForeignKey("TipoServicoClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoMarcacao");

                    b.Navigation("Profissional");

                    b.Navigation("SubsistemaSaude");

                    b.Navigation("TipoServicoClinico");
                });

            modelBuilder.Entity("ClinicAPI.Model.PedidoMarcacao", b =>
                {
                    b.HasOne("ClinicAPI.Model.Utente", "Utente")
                        .WithMany("PedidoMarcacao")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("ClinicAPI.Model.Utente", b =>
                {
                    b.HasOne("ClinicAPI.Model.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ClinicAPI.Model.PedidoMarcacao", b =>
                {
                    b.Navigation("ActosClinicos");
                });

            modelBuilder.Entity("ClinicAPI.Model.Profissional", b =>
                {
                    b.Navigation("ActosClinicos");
                });

            modelBuilder.Entity("ClinicAPI.Model.SubsistemaSaude", b =>
                {
                    b.Navigation("ActosClinicos");
                });

            modelBuilder.Entity("ClinicAPI.Model.TipoServicoClinico", b =>
                {
                    b.Navigation("ActosClinicos");
                });

            modelBuilder.Entity("ClinicAPI.Model.Utente", b =>
                {
                    b.Navigation("PedidoMarcacao");
                });
#pragma warning restore 612, 618
        }
    }
}
